## Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [1]:
import numpy as np
arr1 = np.arange(10, 41)
arr2 = np.arange(220, 251)
sum_array = arr1 + arr2
print(sum_array)

[230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288 290]


2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [2]:
arr_2d = np.arange(100, 170).reshape(10, 7)
print(arr_2d)

[[100 101 102 103 104 105 106]
 [107 108 109 110 111 112 113]
 [114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134]
 [135 136 137 138 139 140 141]
 [142 143 144 145 146 147 148]
 [149 150 151 152 153 154 155]
 [156 157 158 159 160 161 162]
 [163 164 165 166 167 168 169]]


3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [3]:
even_arr = np.arange(2, 51, 2)
odd_arr = np.arange(1, 51, 2)
mult_arr = even_arr * odd_arr
print(mult_arr)

[   2   12   30   56   90  132  182  240  306  380  462  552  650  756
  870  992 1122 1260 1406 1560 1722 1892 2070 2256 2450]


4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [4]:
random_arr = np.random.randint(1, 1001, size=(40, 5))
filtered_arr = random_arr[(random_arr % 2 == 0) & (random_arr % 5 == 0)]
print(filtered_arr)

[ 210  470  460  790  400  300  160  670  660  420  750  850  170  510
  270  950 1000  350  100  470]
